#设置端口号
server:
  port: 8001
#连接mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #password: mapbar
    password: mapbar
    url: jdbc:mysql://localhost:3306/publicsurvery_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://172.19.165.223/publicsurvery_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/**/*.xml


